services:
  postgres-test:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    command: >
      sh -c "docker-entrypoint.sh postgres &
             sleep 5 &&
             psql -U ${DB_USERNAME} -d ${DB_NAME} -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' &&
             wait"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data:
