# Exported from Render on 2025-03-15T18:19:11Z
databases:
  - name: goit-fullstack-final-project-db
    databaseName: goit_fullstack_final_project_db
    user: goit_fullstack_final_project_db_user
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: '16'
services:
  - type: web
    name: goit-fullstack-final-project-backend
    runtime: node
    repo: https://github.com/kazamov/goit-fullstack-final-project
    plan: free
    region: frankfurt
    buildCommand: npm ci --ignore-scripts && npx nx run backend:build --configuration=production
    startCommand: node apps/backend/dist/main.js
    healthCheckPath: /
    previews:
      generation: automatic
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        fromService:
          name: goit-fullstack-final-project-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: DB_PORT
        fromDatabase:
          name: goit-fullstack-final-project-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: goit-fullstack-final-project-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: goit-fullstack-final-project-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: goit-fullstack-final-project-db
          property: database
      - key: DB_HOST
        fromDatabase:
          name: goit-fullstack-final-project-db
          property: host
      - key: DB_ENABLE_SSL
        value: 'false'
      - key: SKIP_INSTALL_DEPS
        value: 'true'
  - type: web
    name: goit-fullstack-final-project-frontend
    runtime: static
    repo: https://github.com/kazamov/goit-fullstack-final-project
    buildCommand: npm ci --ignore-scripts && npx nx run frontend:build --skip-nx-cache
    staticPublishPath: apps/frontend/dist
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: goit-fullstack-final-project-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: SKIP_INSTALL_DEPS
        value: 'true'
version: '1'
