# Exported from Render on 2025-03-15T18:19:11Z
databases:
- name: goit-fullstack-final-project-db
  databaseName: goit_fullstack_final_project_db
  user: goit_fullstack_final_project_db_user
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: goit-fullstack-final-project-backend
  runtime: node
  repo: https://github.com/kazamov/goit-fullstack-final-project
  plan: free
  region: frankfurt
  buildCommand: npm ci && npx nx run backend:build --configuration=production
  startCommand: npx nx run backend:serve --configuration=production
  healthCheckPath: /
- type: web
  name: goit-fullstack-final-project-frontend
  runtime: static
  repo: https://github.com/kazamov/goit-fullstack-final-project
  buildCommand: npm ci && npx nx run frontend:build
  staticPublishPath: apps/frontend/dist
  previews:
    generation: automatic
version: "1"
